### ISSUE TITLE
About python environment

### ISSUE THREAD

**Issue by yxt916** [khayliang/person_tracking_ros#1]
May be  ros doesn't work well with python3, so I have to use python2, but errors coming. Please help me

**Comment by khayliang** [comment]
hello, may I know your ROS version? You can use python3 with ros melodic. Install virtualenv inside python 3  and create the env somewhere accessible.  Then inside`/bin/yolov3_deepsort_ros.py` change the shebang into your env path 
```
#!/[path-to-virtualenv]/bin/python
```

**Comment by yxt916** [comment]
Python3 worked! 
I just followed the requiremwnt list strictly, fixed the path and installed every thing. 
The speed is good, over 20 fps.  
But sometimes the person tracking will lost for a second and the number will +1.

**Comment by khayliang** [comment]
glad I could help. The number increments because you havent selected the person as a target.  You're supposed to call the service `/person_tracking/choose_target` and give it the number of the person you want to track, and it will only track that person.

**Comment by yxt916** [comment]
I want to use the topic "/person_tracking/bbox_center", like converting this center in image to a point in 3Dpointcloud. How did you use it? Could you help me?

**Comment by khayliang** [comment]
I recommend you use some sort of RGB-D camera, so you can use the RGB image from the camera to track the person, get the center, and use the corresponding depth image to get the distance of the person to the camera.
