### ISSUE TITLE
[ERROR] Dropping connection

### ISSUE THREAD

**Issue by akamob** [khayliang/person_tracking_ros#3]
Hi, Thank you for the awesome work.

I have a logitech webcam and use **video_stream_opencv** to run roslaunch video_stream_opencv webcam.launch command. My image topic is **/webcam/image_raw**, so I change args="--img_topic **/camera/image_raw/compressed** --save_results" to args="--img_topic **/webcam/image_raw** --save_results" in person_tracker.launch.

But I got:
[ERROR] [1642582391.637392414]: Client [/person_tracker] wants topic /webcam/image_raw to have datatype/md5sum [sensor_msgs/CompressedImage/8f7a12909da2c9d3332d540a0977563f], but our version has [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743]. Dropping connection.
![question_2 from 2022-01-19 16-58-04](https://user-images.githubusercontent.com/49118957/150114682-bb745152-bc4f-41a2-b27d-5be639914846.png)

In readme.md mentioned: _Only compressed image is supported_ and _Ensure that your image topic is correctly set to your preferred tracker_ so I'm wondering if I miss something in my setup?

May i have your suggestions to fix this problem?
Any help is much appreciated:)

**Comment by khayliang** [comment]
@akamob hey. Input only accepts compressed image data type. You're using uncompressed data, so it won't work.

I used compressed image last time as I was having trouble using plain raw image. I forgot the reason why.
