### ISSUE TITLE
High CPU load 

### ISSUE THREAD

**Issue by waiyc** [khayliang/person_tracking_ros#4]
Hi,

The CPU load is normal if I run everything under your package.
However, I faced high CPU load issue (almost 100% with 20 cores CPU) when i try the `person_tracking.py` outside of your package.
Any idea what might be the cause and how to overcome this?

**Comment by winstxnhdw** [comment]
have u tried turning your computer on and off?

**Comment by waiyc** [comment]
Found out that is nn_budget=100 causes the high CPU usage, reduced to 10 solve it.
